{% set version = "1.0-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-orthopolynom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/orthopolynom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/orthopolynom/orthopolynom_{{ version }}.tar.gz
  sha256: 17576157374c927da2959459caf2ed161b49a4a7768ea3d3fbe47656cafacc5b

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-polynom
  run:
    - r-base
    - r-polynom

test:
  commands:
    - $R -e "library('orthopolynom')"           # [not win]
    - "\"%R%\" -e \"library('orthopolynom')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=orthopolynom
  license: GPL-2.0-or-later
  summary: A collection of functions to construct sets of orthogonal polynomials and their recurrence relations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
