appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: xj838yiMjIHaTiI9VXlVKYxjiDGy8XUTLq33YzEKBqgcyTTqNfif7OoARkXWC92PMgYNEd6xdCJa1h/tYhFxpkCz/cSKVK8+hwJEeJXWypFNWzou38My6GKOhV/qYVg1NqMy3F01uJ9MKXI1o0HQcVj0OrMKTZ1wXA4L3xMoU+nuW+6h+MWlpXRffHIQU+rTsNNiX+rxWRNmj2cznuXQR8WZsLaqKk8PWMthZiaKsIWgQKSmF3eeroqlZUnZKlD+PwiWCNaCLxfLT0sPooEBo4VXhcjXvxdxAmFM5RfaTo03ja5vC5ZE1dPnR4JfUIr/24b4YF3/1LJKf14mL90tt+bPN3+8vb2YwumApVno6CBKW+0QRPCW0lq2uCoI7UMFczKTDUnHd1cbODPzcPNAKwS/Ly7kXm54N++CgTlw4dnZjFagGav74bmulVr34bdy1PXF45tVrdCFVgptuz+yymRnf8WHjl1GcXrgCJhwQJVikrlXnd5XTgtUAuOB9d4DTokA496g7IlwggB0kTzj0uYuVXQu/abgv7bisvxZgiAhvw5w79+7dWb1eT4QAFSqn+bz4NVLHFhwaloAGG+hKQfljCniypxX/nAbt9u2sBkY7fSmxTJAJ2I6kTa9npSdR8e6hCfCFrdPlJaS63i231kj9cBV5b8i2/BiEEz8f8s=
